server:
  port: 8080

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: 
              - "http://localhost:*"
              - "http://127.0.0.1:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          uri: lb://UsersService
          predicates:
            - Path=/api/users/**
        
        - id: produit-service
          uri: lb://ProduitService
          predicates:
            - Path=/api/produits/**, /api/images/**
        
        - id: carte-service
          uri: lb://CarteService
          predicates:
            - Path=/api/carte/**
        
        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/api/orders/**
        
        - id: paiement-service
          uri: lb://paiement
          predicates:
            - Path=/api/paiements/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway

# Firebase configuration
firebase:
  credentials:
    path: firebase-credentials.json

# Logging for security
logging:
  level:
    com.example.venteEnLigne.APIGateway.filter: DEBUG