server:
  port: 8083

spring:
  application:
    name: CarteService
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
