server:
  port: 8761

spring:
  application:
    name: EurekaServer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
    prefer-ip-address: false
  server:
    enable-self-preservation: false
