server:
  port: 8082

spring:
  application:
    name: ProduitService
  data:
    mongodb:
      uri: mongodb://mongodb:27017/produits_db
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
